### ISSUE TITLE
Three monitors don't fit properly on the pop up

### ISSUE THREAD

**Issue by rp1231** [sidit77/rusty-twinkle-tray#3] opened 2024-01-29 12:34 UTC
The pop up doesn't fit 3 monitors properly:
![Screenshot 2024-01-29 180334](https://github.com/sidit77/rusty-twinkle-tray/assets/47380919/f715dc4d-f2c3-4b7a-a549-db25a7dba984)

**Comment by sidit77** [comment] 2024-01-29 15:27
Strange. When I add a few extra dummy monitors everything seems to scale fine so I'm not entirely sure what goes wrong here.
![image](https://github.com/sidit77/rusty-twinkle-tray/assets/5053369/9cfa4478-335a-40f3-92cf-c0b60184ccf3)

**Comment by sidit77** [comment] 2024-01-29 16:50
Could you pull from main and try again? I added an extra log statement to the function that changes the window size.

**Comment by sidit77** [comment] 2024-01-29 17:34
> the text appears only when I click on the pop up

It's actually already there, it just has the same color as the background. This is a combination of two issues:

1. The Acylic transparency effect is only active when the window is focus, otherwise it uses a fallback color which is currently pure white if you system theme is set to light. I plan to change that in the future but wanted to do it right and find some source for the correct shade of white instead of just eyeballing it.
2. The controls accidentally always defaulted to a dark theme (= white text) regardless of the current background theme. This was an oversight and should now be fixed.

Generally theming is still quite unfinished an requires more work.

> I think I've found the cause of the issue, it isn't the screen resolution but the screen scaling.

I just tested it and can reproduce the bug now and added it to the todo list,

> I try clicking on the space outside the popup after clicking on the tray icon, but it doesn't get dismissed. It only gets dismissed after I click on the pop up and then click somewhere else.

Yes. The popup hides itself when it loses the input focus however this obviously only works if it has the focus in the first place. I don't know why it doesn't automatically focus for you after it opens. It works for me. I suspect the issue is that some other program interferes with it, 
While this is pretty annoying I would consider this only a minor bug as you'd usually interact with the popup before dismissing it.

**Comment by sidit77** [comment] 2024-01-29 17:53
Now the display scaling issue is fixed and only the focus issue should remain.

**Comment by sidit77** [comment] 2024-01-29 18:06
I think we can close it as the main issue is resolved and the other stuff is on the todo list.

**Closed by sidit77** 2024-01-29 18:06 UTC
